apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    database: market
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    secureJsonData:
      password: "postgres"